apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: devops
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 10s
      # NOTE: prometheus queries return results in the form of a vector.
      # So it is common to access the index 0 of the returned array to obtain the value
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://monitoring-prometheus-stac-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{job="{{args.service-name}}", status=~"2.*|3.*"}[1m])) 
            / 
            sum(rate(http_requests_total{job="{{args.service-name}}"}[1m]))
