apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "grafana-cert"
spec:
  rules:
    - host: grafana.mailscale.online
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: monitoring-prometheus-stack-grafana
                port:
                  number: 80
